<?xml version="1.0"?>
<package format="2">
  <name>panda_benchmark_moveit</name>
  <version>0.0.1</version>
  <description>MoveIt bringup wrapper for Panda benchmarking with OMPL vs DGM.</description>

  <maintainer email="you@example.com">User</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roslaunch</depend>
  <depend>moveit_ros_move_group</depend>
  <depend>moveit_ros_planning</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_msgs</depend>
  <depend>rviz</depend>
  <depend>moveit_resources_panda_description</depend>
  <depend>moveit_resources_panda_moveit_config</depend>
  <depend>xacro</depend>

  <depend>object_tracking</depend>

  <export/>
</package>
